services:
  - type: web
    name: generic-pim
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=data/pim.db
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1 