name: Fly Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: fly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly (if token provided)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if [ -z "$FLY_API_TOKEN" ]; then
            echo "FLY_API_TOKEN not set; skipping deploy."
            exit 0
          fi
          flyctl deploy --remote-only --auto-confirm 